autoclip: false
autoimport: false
cliptimeout: 45
exportkeys: true
nopager: false
notifications: true
parsing: true
path: /home/kurojishi/.local/share/gopass/stores/root
safecontent: false
mounts: {}
